name: DVC Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "Data-Pipeline/**"

jobs:
  dvc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install dvc[gs]
        pip install -r requirements.txt

    - name: Setup GCP credentials
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        printf '%s' "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

    - name: DVC pull
      run: |
        cd Data-Pipeline
        dvc pull

    - name: Run DVC pipeline
      run: |
        cd Data-Pipeline
        dvc repro

    - name: DVC push
      run: |
        cd Data-Pipeline
        dvc push